name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_URL }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            mkdir ~/chess_con_matchmaker
            cd ~/chess_con_matchmaker
            
            pm2 stop "CnC4-Matchmaking-Server"
            pm2 delete "CnC4-Matchmaking-Server"
            
            git init
            git pull https://github.com/Dirakon/CnC4-Matchmaking-Server.git
            npm i
            
            pm2 start npm --name "CnC4-Matchmaking-Server" -- dev
